pokemon_inventory/models.py
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate

import uuid

from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash

import secrets

from flask_login import UserMixin, LoginManager

from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String(150), nullable = True, default = '')
    last_name = db.Column(db.String(150), nullable = True, default = '')
    username = db.Column(db.String(150), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False, default = '')
    password = db.Column(db.String(150), nullable = True, default='')
    g_auth_verify = db.Column(db.Boolean, default = False)
    token = db.Column(db.String, default = '', unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, email, username = '', first_name = '', last_name = '', id='', password = '', token = '', g_auth_verify = False):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.username = username
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify

    def set_token(self, length):
        return secrets.token_hex(length)
    def set_id(self):
        return str(uuid.uuid4())
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    def __repr__(self):
        return f"User {self.email} has been added to the database!"

pokemon_inventory/forms.py
from ast import Pass
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Email

class UserLoginForm(FlaskForm):
    email = StringField('Email', validators = [InputRequired(), Email()])
    username = StringField('Username', validators = [InputRequired()])
    password = PasswordField('Password', validators = [InputRequired()])
    submit_button = SubmitField()

pokemon_inventory/__init__.py
from flask import Flask
from .site.routes import site
from config import Config
from .authentication.routes import auth
from .api.routes import api

from flask_migrate import Migrate

from .models import db as root_db, login_manager, ma


app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
app.config.from_object(Config)

root_db.init_app(app)

migrate = Migrate(app, root_db)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin'

ma.init_app(app)

pokemon_inventory/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/getdata')

def getdata():
    return{'some':'value'}

pokemon_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pokemon_inventory.forms import UserLoginForm
from pokemon_inventory.models import User, db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(email, username, password)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()
            flash(f"You have successfully created a user account {username}", 'user-created')

            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(email, username, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid Form Data or User Does Not Exist, Please Check Your Form or Sign Up")
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

pokemon_inventory/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/Donate')
def Donate():
    return render_template('Donate.html')

pokemon_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>
    <nav class="ct-nav bg-danger">
        <div>
            <img src="../static/Images/icon-1.png" alt="">
        </div>


    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home')}}">
                <li class="text-warning">Pokemon Collector Project</li>
            </a>
            <a href="{{ url_for('site.Donate') }}">
                <li class="text-warning">Donate</li>
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('site.profile') }}">
                <li class ="text-warning">Profile</li>
            </a>
            <a href="{{ url_for('auth.logout') }}">
                <li class="text-warning">Log Out</li>
            </a>
            {% else %}
            <a href="{{ url_for('auth.signin') }}">
                <li class="text-warning">Sign-In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li class="text-warning">Sign-up</li>
            </a>
            {% endif %}
        </ul>
    </div>
    </nav>
    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

pokemon_inventory/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter email here...") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter username here...") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter password here...") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>